### ISSUE TITLE
Question about patch extraction blog

### ISSUE THREAD

**Issue by javierttgg** [ducha-aiki/wide-baseline-stereo-blog#18]
Hi Dmytro, thanks a lot for your [blog on patch extraction](https://ducha-aiki.github.io/wide-baseline-stereo-blog/2020/07/22/patch-extraction.html). I found it to be really useful :)

If you have the time, I'm curious about some points to see if I have understood the process:

1. Is it correct to say that one motivation behind blurring the patches is to keep only the information that will be present at different scales?
2. The part of the image which appears in the patch is determined only by the keypoint scale (LAF scale, $\lambda$)? If yes, if we want to extract a patch of size $S\times S$ with $2\lambda \neq S$ then the patch should be resized to $S\times S$?
3. Lastly, when the LAF scale is unknown (e.g. when the keypoints are extracted with networks like Superpoint), may it be detrimental to fix the same value of $\lambda$ to every predicted keypoint? 
I have come up with this question after seeing how [Key.Net](https://github.com/axelBarroso/Key.Net-Pytorch) (IMO a great work, I reference it just to exemplify my question) perform the patch extraction to describe their keypoints. [Here](https://github.com/axelBarroso/Key.Net-Pytorch/blob/74fe0a75998445bb47b74b642b764543b25dc90a/model/extraction_tools.py#L82-L83) the scale is set to a fix value. 
After reading your blog, my gut feeling tells me that this may incurr in unneeded information losses when blurring the patches when the fixed scale does not match its true value.

Thanks again and apologies for the number of (and maybe basic 😅) questions.

**Comment by ducha-aiki** [comment]
Hi,

1) Yes. For more detailed motivation I recommend you to check this paper https://arxiv.org/abs/1904.11486 
2) Yes. Or more precise, we create the grid of size SxS, which covers the area of  λ x λ in the original image. Simple example: we want patch of 2x2 size from scale 2.5 x 2.5. Then we have to interpolate pixels values at locations (-1.25, -1.25), (-1.25, 1.25), (1.25, -1.25), (1.25 ,1.25), considering the (0, 0) as a center of keypoint.

3. It is actually what is done for many local features, e.g. ORB, R2D2, etc. That would not be precise, but not very bad either. It is also kind of irrelevant for SuperPoint, as it extracts descriptor together with keypoint, so you don't need to extract any patches. What you can do, is to underblur, rather than overblur if you decide to extract patches anyway. 

You can get some additional information from my CVPR tutorial on the local affine features, [slides are here](https://docs.google.com/presentation/d/1p6wrkrm3xzjurpUWyoDxFYyWZV-8yfjZ/edit?usp=sharing&ouid=115298473833145933100&rtpof=true&sd=true)

**Comment by javierttgg** [comment]
Thanks a lot for the responses and links. They have clarified all my questions :)

If I may,  after reading your point 3,  I'm left just with one question. 
I understand that in Superpoint there is no need to extract patches. However, why is it needed in R2D2? 
After reading its paper, they seem to compute descriptors for every pixel, as in Superpoint. On the other hand, their multiscale strategy does not seem to use blurring (in [this lines of code](https://github.com/naver/r2d2/blob/0ff8f6afcbea91f19613d0cb7d93143a977830f5/extract.py#L96-L97) they perform the resizing).

PS: really useful slides to gain and reinforce knowledge and really interesting paper :).

**Comment by ducha-aiki** [comment]
R2D2 does not not need scale to get descriptors, you are right. 
However, R2D2 does output the scale as keypoint parameter.

For the multi scale - they don't need to do the blurring, because another way to do the anti-aliasing (although not as precise), is to just use bilinear interpolation, but do it in stages - downscale 1.5x , then again 1.5x, then 1.5 and so on.

**Comment by javierttgg** [comment]
I see that knowing the scale can be benefitial for matching. OTOH I will have a look at using bilinear interpolation in that way. Thanks for all the help :)
